/*Iniciando a Modelagem fisica */ 

CREATE DATABASE PROJETO;

USE PROJETO

CREATE TABLE CLIENTE (
    TELEFONE VARCHAR(30),
    CPF INT(11),
    SEXO CHAR(1),
    EMAIL VARCHAR (30),
    NOME VARCHAR (30),
    ENDERECO VARCHAR(100)

);

SHOW TABLES; 


DESC CLIENTE


/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES('22923110',988638273,'M','JOAO@GMAIL.COM','JOAO','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('25078869',541521456,'F','CELIA@GMAIL.COM','CELIA','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('58748895',885755896,'M',NULL,'JORGE','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');


/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);


/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

    ('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                          ('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');


INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',99999999999);

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',22222222222);



SELECT NOME, SEXO, EMAIL FROM CLIENTE

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE


SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';


SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'OSCAR CURRY%';


/* Realizando atualização nos dados */

UPDATE CLIENTE SET EMAIL = 'JORGE@IG.COM.BR'
WHERE NOME = 'JORGE';

UPDATE CLIENTE SET EMAIL = 'LILIAN@HOTMAIL.COM'
WHERE NOME = 'LILIAN';